#!/bin/bash

# Left click: open Bluetooth manager
if [ "$BLOCK_BUTTON" = "1" ]; then
  blueman-manager &
  # exit
fi

# Right click: toggle Bluetooth
if [ "$BLOCK_BUTTON" = "3" ]; then
  rfkill toggle bluetooth
  # exit
fi

# Check Bluetooth status
if rfkill list bluetooth | grep -q "Soft blocked: yes"; then
  echo "[󰂲]"
else
  echo "[󰂯]"
fi

# Short text (used for i3bar if bar space is limited)
echo ""

# Color (text color in hex)
echo "#8CAAEE"
