#!/bin/bash

STATE_FILE="/tmp/i3blocks-clock-state"

# Toggle format on right click
if [ "$BLOCK_BUTTON" = "1" ]; then
  if [[ -f "$STATE_FILE" && "$(cat $STATE_FILE)" = "date" ]]; then
    echo "time" > "$STATE_FILE"
  else
    echo "date" > "$STATE_FILE"
  fi
fi

# Default state
if [ ! -f "$STATE_FILE" ]; then
  echo "time" > "$STATE_FILE"
fi

STATE=$(cat "$STATE_FILE")

if [ "$STATE" = "date" ]; then
  echo "[ $(date '+%Y-%m-%d') ]"
else
  echo "[ 󱑏 $(date '+%I:%M %p') ]"
fi
